export const data = [
  { name: "театр" },
  { name: "концерт" },
  { name: "детям" },
  { name: "Спорт" },
  { name: "Туризм" },
  { name: "Музей" },
  { name: "Развитие" },
  { name: "Кино" },
  { name: "Новости" },
];
export const data2 = [
  {
    name: "Мирбек Атабеков",
    type: "концерт",
    city: "Бишкек",
    id: 1,
    Main: "Главный",
    price: "2500-5500",
    data: " 06 марта 2023",
    img: "/img.jpeg",
  },
  {
    name: "Лучшие хиты ",
    type: "концерт",
    city: "Бишкек",
    id: 2,
    price: "1000-3500",
    data: "28 апреля 2023",
    img: "/img2.jpg",
    Main: "Главный",
  },
  {
    name: "Ваня Усович",
    type: "концерт",
    city: "Бишкек",
    id: 3,
    price: "1500-5000",
    data: "29 апреля 2023",
    img: "/img3.jpg",
    Main: "Главный",
  },
  {
    name: "Валерий Меладзе",
    type: "концерт",
    city: "Бишкек",
    id: 4,
    price: "2100-9100",
    data: "16 мая 2023",
    img: "/img4.jpg",
    Main: "Большой",
  },
  {
    name: "Евгений Чебатков",
    type: "концерт",
    city: "Бишкек",
    id: 5,
    price: "1500-5100",
    data: "18 мая 2023",
    img: "/img5.jpg",
    Main: "Большой",
  },
  {
    name: "Zivert",
    type: "концерт",
    city: "Бишкек",
    id: 6,
    price: "500-9000 ",
    data: "23 сентября 2023",
    img: "/img6.jpg",
    Main: "Главный",
  },
  {
    name: "Семейный Шоу",
    type: "детям",
    city: "Бишкек",
    id: 7,
    price: "800-2000 ",
    data: "18 марта 2023",
    img: "/img7.jpg",
    Main: "Главный",
  },
  {
    name: "Фиксики",
    type: "детям",
    city: "Бишкек",
    id: 8,
    price: "900-3500",
    data: "02 апреля 2023",
    img: "/img8.jpg",
    Main: "Большой",
  },
  {
    name: "АЛДА ЖАШ ЖУБАЙЛАР,",
    type: "театр",
    city: "Бишкек",
    id: 9,
    price: "300",
    data: "02 апреля 2023",
    img: "/img9.png",
    Main: "Главный",
  },
  {
    name: "Кичинекей адамдын ",
    type: "театр",
    city: "Бишкек",
    id: 10,
    price: "300",
    data: "25 февраля 2023",
    img: "/img10.jpg",
    Main: "Главный",
  },
  {
    name: "Төлгө",
    type: "театр",
    city: "Бишкек",
    id: 11,
    price: "300",
    data: "02 марта 2023",
    img: "/img11.jpg",
    Main: "Главный",
  },
  {
    name: "Мастер и Маргарита",
    type: "театр",
    city: "Бишкек",
    id: 12,
    price: "1200-3500",
    data: "04 марта 2023",
    img: "/img12.jpg",
    Main: "Главный",
  },
  {
    name: "Мастер и Маргарита",
    type: "театр",
    city: "Бишкек",
    id: 13,
    price: "300",
    data: "14 марта 2023",
    img: "/img13.jpg",
    Main: "Главный",
  },
  {
    name: "Курманжан Датка",
    type: "театр",
    city: "Бишкек",
    id: 14,
    price: "300",
    data: "15 марта 2023",
    img: "/img14.jpg",
    Main: "Главный",
  },
];
